export function fabricIconsBarcodes() {
    return [
        {
            name: 'Основное',
            category: true,
            items: [
                { name: 'Datamatrix', path: '/assets/barcodes/datamatrix.svg', meta: 'datamatrix', meta_type: '' },
                { name: 'QR', path: '/assets/barcodes/qr.svg', meta: 'qr', meta_type: '' },
            ],
        },
        {
            name: 'Баркоды',
            category: true,
            items: [
                { name: 'C39', path: '/assets/barcodes/C39.svg', meta: 'barcode', meta_type: 'C39' },
                { name: 'C39+', path: '/assets/barcodes/C39.svg', meta: 'barcode', meta_type: 'C39+' },
                { name: 'C39E', path: '/assets/barcodes/C39E.svg', meta: 'barcode', meta_type: 'C39E' },
                { name: 'C39E+', path: '/assets/barcodes/C39E.svg', meta: 'barcode', meta_type: 'C39E+' },
                { name: 'C93', path: '/assets/barcodes/C93.svg', meta: 'barcode', meta_type: 'C93' },
                { name: 'S25', path: '/assets/barcodes/S25.svg', meta: 'barcode', meta_type: 'S25' },
                { name: 'S25+', path: '/assets/barcodes/S25.svg', meta: 'barcode', meta_type: 'S25+' },
                { name: 'I25', path: '/assets/barcodes/I25.svg', meta: 'barcode', meta_type: 'I25' },
                { name: 'I25+', path: '/assets/barcodes/I25.svg', meta: 'barcode', meta_type: 'I25+' },
                { name: 'C128', path: '/assets/barcodes/C128.svg', meta: 'barcode', meta_type: 'C128' },
                { name: 'C128A', path: '/assets/barcodes/C128A.svg', meta: 'barcode', meta_type: 'C128A' },
                { name: 'C128B', path: '/assets/barcodes/C128B.svg', meta: 'barcode', meta_type: 'C128B' },
                { name: 'C128C', path: '/assets/barcodes/C128C.svg', meta: 'barcode', meta_type: 'C128C' },
                { name: 'GS1-128', path: '/assets/barcodes/GS1-128.svg', meta: 'barcode', meta_type: 'GS1-128' },
                { name: 'EAN2', path: '/assets/barcodes/EAN2.svg', meta: 'barcode', meta_type: 'EAN2' },
                { name: 'EAN5', path: '/assets/barcodes/EAN5.svg', meta: 'barcode', meta_type: 'EAN5' },
                { name: 'EAN8', path: '/assets/barcodes/EAN8.svg', meta: 'barcode', meta_type: 'EAN8' },
                { name: 'EAN13', path: '/assets/barcodes/EAN13.svg', meta: 'barcode', meta_type: 'EAN13' },
                { name: 'UPCA', path: '/assets/barcodes/UPC-A.svg', meta: 'barcode', meta_type: 'UPCA' },
                { name: 'UPCE', path: '/assets/barcodes/UPCE.svg', meta: 'barcode', meta_type: 'UPCE' },
                { name: 'MSI', path: '/assets/barcodes/MSI.svg', meta: 'barcode', meta_type: 'MSI' },
                { name: 'MSI+', path: '/assets/barcodes/MSI.svg', meta: 'barcode', meta_type: 'MSI+' },
                { name: 'POSTNET', path: '/assets/barcodes/POSTNET.svg', meta: 'barcode', meta_type: 'POSTNET' },
                { name: 'PLANET', path: '/assets/barcodes/PLANET.svg', meta: 'barcode', meta_type: 'PLANET' },
                { name: 'RMS4CC', path: '/assets/barcodes/RMS4CC.svg', meta: 'barcode', meta_type: 'RMS4CC' },
                { name: 'KIX', path: '/assets/barcodes/KIX.svg', meta: 'barcode', meta_type: 'KIX' },
                { name: 'IMB', path: '/assets/barcodes/IMB.svg', meta: 'barcode', meta_type: 'IMB' },
                { name: 'CODABAR', path: '/assets/barcodes/CODABAR.svg', meta: 'barcode', meta_type: 'CODABAR' },
                { name: 'CODE11', path: '/assets/barcodes/CODE11.svg', meta: 'barcode', meta_type: 'CODE11' },
                { name: 'PHARMA', path: '/assets/barcodes/PHARMA.svg', meta: 'barcode', meta_type: 'PHARMA' },
                { name: 'PHARMA2T', path: '/assets/barcodes/PHARMA2T.svg', meta: 'barcode', meta_type: 'PHARMA2T' },
            ],
        },
    ];
}
