export function fabricIconsBarcodes() {
    return [
        {
            name: 'Основное',
            category: true,
            items: [
                { name: 'Datamatrix', path: '/assets/barcodes/datamatrix.svg', meta: 'datamatrix', meta_type: '' },
                { name: 'QR', path: '/assets/barcodes/qr.svg', meta: 'qr', meta_type: '' },
            ],
        },
        {
            name: 'Баркоды',
            category: true,
            items: [
                { name: 'C39', path: '/assets/barcode/C39.svg', meta: 'barcode', meta_type: 'C39' },
                { name: 'C39+', path: '/assets/barcode/C39.svg', meta: 'barcode', meta_type: 'C39+' },
                { name: 'C39E', path: '/assets/barcode/C39E.svg', meta: 'barcode', meta_type: 'C39E' },
                { name: 'C39E+', path: '/assets/barcode/C39E.svg', meta: 'barcode', meta_type: 'C39E+' },
                { name: 'C93', path: '/assets/barcode/C93.svg', meta: 'barcode', meta_type: 'C93' },
                { name: 'S25', path: '/assets/barcode/S25.svg', meta: 'barcode', meta_type: 'S25' },
                { name: 'S25+', path: '/assets/barcode/S25.svg', meta: 'barcode', meta_type: 'S25+' },
                { name: 'I25', path: '/assets/barcode/I25.svg', meta: 'barcode', meta_type: 'I25' },
                { name: 'I25+', path: '/assets/barcode/I25.svg', meta: 'barcode', meta_type: 'I25+' },
                { name: 'C128', path: '/assets/barcode/C128.svg', meta: 'barcode', meta_type: 'C128' },
                { name: 'C128A', path: '/assets/barcode/C128A.svg', meta: 'barcode', meta_type: 'C128A' },
                { name: 'C128B', path: '/assets/barcode/C128B.svg', meta: 'barcode', meta_type: 'C128B' },
                { name: 'C128C', path: '/assets/barcode/C128C.svg', meta: 'barcode', meta_type: 'C128C' },
                { name: 'GS1-128', path: '/assets/barcode/GS1-128.svg', meta: 'barcode', meta_type: 'GS1-128' },
                { name: 'EAN2', path: '/assets/barcode/EAN2.svg', meta: 'barcode', meta_type: 'EAN2' },
                { name: 'EAN5', path: '/assets/barcode/EAN5.svg', meta: 'barcode', meta_type: 'EAN5' },
                { name: 'EAN8', path: '/assets/barcode/EAN8.svg', meta: 'barcode', meta_type: 'EAN8' },
                { name: 'EAN13', path: '/assets/barcode/EAN13.svg', meta: 'barcode', meta_type: 'EAN13' },
                { name: 'UPCA', path: '/assets/barcode/UPC-A.svg', meta: 'barcode', meta_type: 'UPCA' },
                { name: 'UPCE', path: '/assets/barcode/UPCE.svg', meta: 'barcode', meta_type: 'UPCE' },
                { name: 'MSI', path: '/assets/barcode/MSI.svg', meta: 'barcode', meta_type: 'MSI' },
                { name: 'MSI+', path: '/assets/barcode/MSI.svg', meta: 'barcode', meta_type: 'MSI+' },
                { name: 'POSTNET', path: '/assets/barcode/POSTNET.svg', meta: 'barcode', meta_type: 'POSTNET' },
                { name: 'PLANET', path: '/assets/barcode/PLANET.svg', meta: 'barcode', meta_type: 'PLANET' },
                { name: 'RMS4CC', path: '/assets/barcode/RMS4CC.svg', meta: 'barcode', meta_type: 'RMS4CC' },
                { name: 'KIX', path: '/assets/barcode/KIX.svg', meta: 'barcode', meta_type: 'KIX' },
                { name: 'IMB', path: '/assets/barcode/IMB.svg', meta: 'barcode', meta_type: 'IMB' },
                { name: 'CODABAR', path: '/assets/barcode/CODABAR.svg', meta: 'barcode', meta_type: 'CODABAR' },
                { name: 'CODE11', path: '/assets/barcode/CODE11.svg', meta: 'barcode', meta_type: 'CODE11' },
                { name: 'PHARMA', path: '/assets/barcode/PHARMA.svg', meta: 'barcode', meta_type: 'PHARMA' },
                { name: 'PHARMA2T', path: '/assets/barcode/PHARMA2T.svg', meta: 'barcode', meta_type: 'PHARMA2T' },
            ],
        },
    ];
}
