export function fabricIconsSpecial() {
    return [
        {
            name: 'Знаки соответствия',
            category: true,
            items: [
                { name: 'Евразийское соответствие', path: '/assets/icons/eac.svg', meta: '', meta_type: '' },
                { name: 'Европейское соответствие', path: '/assets/icons/ce.svg', meta: '', meta_type: '' },
                { name: 'РСТ', path: '/assets/icons/rst.svg', meta: '', meta_type: '' },
                { name: 'РСТ тех.регламент', path: '/assets/icons/rst-tr.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Манипуляционные знаки',
            category: true,
            items: [
                { name: 'Хрупкое', path: '/assets/icons/m-khrupkoe.svg', meta: '', meta_type: '' },
                { name: 'Беречь от влаги', path: '/assets/icons/m-boitsya-vlagi.svg', meta: '', meta_type: '' },
                { name: 'Беречь от солнечных лучей', path: '/assets/icons/m-berech-ot-sol.svg', meta: '', meta_type: '' },
                { name: 'Беречь от излучения', path: '/assets/icons/m-berech-ot-izluchen.svg', meta: '', meta_type: '' },
                { name: 'Пределы температуры', path: '/assets/icons/m-temperat.svg', meta: '', meta_type: '' },
                { name: 'Скоропортящийся груз', path: '/assets/icons/m-skoroport.svg', meta: '', meta_type: '' },
                { name: 'Герметичная упаковка', path: '/assets/icons/m-germetichnaya-upak.svg', meta: '', meta_type: '' },
                { name: 'Крюками не брать', path: '/assets/icons/m-kryukami-ne-brat.svg', meta: '', meta_type: '' },
                { name: 'Место строповки', path: '/assets/icons/m-mesto-stropovki.svg', meta: '', meta_type: '' },
                { name: 'Поднимать тележкой запрещается', path: '/assets/icons/m-zdes-podnimat-tel.svg', meta: '', meta_type: '' },
                { name: 'Верх', path: '/assets/icons/m-verkh.svg', meta: '', meta_type: '' },
                { name: 'Центр тяжести', path: '/assets/icons/m-tsentr-tyazhesti.svg', meta: '', meta_type: '' },
                { name: 'Штабелировать запрещается', path: '/assets/icons/m-shtabelirovat-zap.svg', meta: '', meta_type: '' },
                { name: 'Поднимать непосредственно за груз', path: '/assets/icons/m-podnimat-neposred.svg', meta: '', meta_type: '' },
                { name: 'Открывать здесь', path: '/assets/icons/m-otkryvat-zdes.svg', meta: '', meta_type: '' },
                { name: 'Защищать от радиоактивных источников', path: '/assets/icons/m-zaschischat-ot-ra.svg', meta: '', meta_type: '' },
                { name: 'Не катить', path: '/assets/icons/m-ne-katit.svg', meta: '', meta_type: '' },
                { name: 'Предел штабелирования по массе', path: '/assets/icons/m-shtabelirovanie-o.svg', meta: '', meta_type: '' },
                { name: 'Зажимать здесь', path: '/assets/icons/m-zazhimat-zdes.svg', meta: '', meta_type: '' },
                { name: 'Не зажимать', path: '/assets/icons/m-ne-zazhimat.svg', meta: '', meta_type: '' },
                { name: 'Предел по количеству ярусов в штабеле', path: '/assets/icons/m-predel-po-koliche.svg', meta: '', meta_type: '' },
                { name: 'Вилочные погрузчики не использовать', path: '/assets/icons/m-vilochnye-pogruzc.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Экологические знаки',
            category: true,
            items: [
                { name: 'Зеленая точка', path: '/assets/icons/e-zelenaya-tochka.svg', meta: '', meta_type: '' },
                { name: 'Петля Мебиуса', path: '/assets/icons/e-vtorichnaya-perera.svg', meta: '', meta_type: '' },
                { name: 'Выкидывать в мусорное урну', path: '/assets/icons/e-vykidyvat-v-musorn.svg', meta: '', meta_type: '' },
                { name: 'Бокал-вилка', path: '/assets/icons/e-znak-bokal-vilka.svg', meta: '', meta_type: '' },
                { name: 'Сертификация по экологическим требованиям', path: '/assets/icons/e-stand.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Пластмассы',
            category: true,
            items: [
                { name: 'Полиэтилентерефталат (лавсан)', path: '/assets/icons/recyc-01.svg', meta: '', meta_type: '' },
                { name: 'Полиэтилен высокой плотности', path: '/assets/icons/recyc-02.svg', meta: '', meta_type: '' },
                { name: 'Поливинилхлорид', path: '/assets/icons/recyc-03.svg', meta: '', meta_type: '' },
                { name: 'Полиэтилен низкой плотности', path: '/assets/icons/recyc-04.svg', meta: '', meta_type: '' },
                { name: 'Полипропилен', path: '/assets/icons/recyc-05.svg', meta: '', meta_type: '' },
                { name: 'Полистирол', path: '/assets/icons/recyc-06.svg', meta: '', meta_type: '' },
                { name: 'Сополимер стирола и акрилонитрила', path: '/assets/icons/recyc-06-san.svg', meta: '', meta_type: '' },
                { name: 'Остальные виды пластика', path: '/assets/icons/recyc-07.svg', meta: '', meta_type: '' },
                { name: 'Поликарбонат', path: '/assets/icons/recyc-07-pc.svg', meta: '', meta_type: '' },
                { name: 'АБС-пластик', path: '/assets/icons/recyc-09.svg', meta: '', meta_type: '' },
                { name: 'АБС-пластик', path: '/assets/icons/recyc-09-abs.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Бумага',
            category: true,
            items: [
                { name: 'Гофрированный картон', path: '/assets/icons/recyc-20.svg', meta: '', meta_type: '' },
                { name: 'Прочий картон', path: '/assets/icons/recyc-21.svg', meta: '', meta_type: '' },
                { name: 'Бумага', path: '/assets/icons/recyc-22.svg', meta: '', meta_type: '' },
                { name: 'Вощёная бумага', path: '/assets/icons/recyc-23.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Металлы',
            category: true,
            items: [
                { name: 'Сталь', path: '/assets/icons/recyc-40.svg', meta: '', meta_type: '' },
                { name: 'Алюминий', path: '/assets/icons/recyc-41.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Органические материалы природного происхождения',
            category: true,
            items: [
                { name: 'Древесина', path: '/assets/icons/recyc-50.svg', meta: '', meta_type: '' },
                { name: 'Пробка', path: '/assets/icons/recyc-51.svg', meta: '', meta_type: '' },
                { name: 'Хлопок', path: '/assets/icons/recyc-60.svg', meta: '', meta_type: '' },
                { name: 'Джутовое волокно', path: '/assets/icons/recyc-61.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Стекло',
            category: true,
            items: [
                { name: 'Бесцветное стекло', path: '/assets/icons/recyc-70.svg', meta: '', meta_type: '' },
                { name: 'Зелёное стекло', path: '/assets/icons/recyc-71.svg', meta: '', meta_type: '' },
                { name: 'Коричневое стекло', path: '/assets/icons/recyc-72.svg', meta: '' },
                { name: 'Тёмно-коричневое стекло', path: '/assets/icons/recyc-73.svg', meta: '', meta_type: '' },
                { name: 'Светло-коричневое стекло', path: '/assets/icons/recyc-74.svg', meta: '' },
                { name: 'Стекло с малым содержанием свинца', path: '/assets/icons/recyc-75.svg', meta: '', meta_type: '' },
                { name: 'Хрусталь', path: '/assets/icons/recyc-76.svg', meta: '', meta_type: '' },
                { name: 'Стекло, покрытое медью', path: '/assets/icons/recyc-77.svg', meta: '', meta_type: '' },
                { name: 'Стекло, покрытое серебром', path: '/assets/icons/recyc-78.svg', meta: '', meta_type: '' },
                { name: 'Позолоченное стекло', path: '/assets/icons/recyc-79.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Композиционные материалы',
            category: true,
            items: [
                { name: 'Бумага (картон) / различные материалы', path: '/assets/icons/recyc-80.svg', meta: '', meta_type: '' },
                { name: 'Бумага (картон) / пластик', path: '/assets/icons/recyc-81.svg', meta: '', meta_type: '' },
                { name: 'Бумага (картон) / алюминий', path: '/assets/icons/recyc-82.svg', meta: '', meta_type: '' },
                { name: 'Бумага (картон) / белая жесть', path: '/assets/icons/recyc-83.svg', meta: '', meta_type: '' },
                { name: 'Бумага (картон) / пластик / алюминий', path: '/assets/icons/recyc-84.svg', meta: '', meta_type: '' },
                { name: 'Бумага (картон) / пластик / алюминий / жесть', path: '/assets/icons/recyc-85.svg', meta: '', meta_type: '' },
                { name: 'Пластик / алюминий', path: '/assets/icons/recyc-90.svg', meta: '', meta_type: '' },
                { name: 'Пластик / белая жесть', path: '/assets/icons/recyc-91.svg', meta: '', meta_type: '' },
                { name: 'Пластик / различные металлы', path: '/assets/icons/recyc-92.svg', meta: '', meta_type: '' },
                { name: 'Стекло / пластик', path: '/assets/icons/recyc-95.svg', meta: '', meta_type: '' },
                { name: 'Стекло / алюминий', path: '/assets/icons/recyc-96.svg', meta: '', meta_type: '' },
                { name: 'Стекло / белая жесть', path: '/assets/icons/recyc-97.svg', meta: '', meta_type: '' },
                { name: 'Стекло / различные металлы', path: '/assets/icons/recyc-98.svg', meta: '', meta_type: '' },
            ],
        },
        {
            name: 'Батареи и аккумуляторы',
            category: true,
            items: [
                { name: 'Литиевый элемент', path: '/assets/icons/recyc-b-liion.svg', meta: '', meta_type: '' },
                { name: 'Никель-кадмиевый аккумулятор', path: '/assets/icons/recyc-b-nicd.svg', meta: '', meta_type: '' },
                { name: 'Никель-металл-гидридный аккумулятор', path: '/assets/icons/recyc-b-nimh.svg', meta: '', meta_type: '' },
                { name: 'Свинцово-кислотный аккумулятор', path: '/assets/icons/recyc-b-pb.svg', meta: '', meta_type: '' },
            ],
        },
    ];
}
