export const specIcons = [
    { name: 'Пластмассы', path: '' },
    { name: 'Полиэтилентерефталат (лавсан)', path: '/assets/icons/recyc-01.svg' },
    { name: 'Полиэтилен высокой плотности', path: '/assets/icons/recyc-02.svg' },
    { name: 'Поливинилхлорид', path: '/assets/icons/recyc-03.svg' },
    { name: 'Полиэтилен низкой плотности', path: '/assets/icons/recyc-04.svg' },
    { name: 'Полипропилен', path: '/assets/icons/recyc-05.svg' },
    { name: 'Полистирол', path: '/assets/icons/recyc-06.svg' },
    { name: 'Сополимер стирола и акрилонитрила', path: '/assets/icons/recyc-06-san.svg' },
    { name: 'Остальные виды пластика', path: '/assets/icons/recyc-07.svg' },
    { name: 'Поликарбонат', path: '/assets/icons/recyc-07-pc.svg' },
    { name: 'АБС-пластик', path: '/assets/icons/recyc-09.svg' },
    { name: 'АБС-пластик', path: '/assets/icons/recyc-09-abs.svg' },

    { name: 'Бумага', path: '' },
    { name: 'Гофрированный картон', path: '/assets/icons/recyc-20.svg' },
    { name: 'Прочий картон', path: '/assets/icons/recyc-21.svg' },
    { name: 'Бумага', path: '/assets/icons/recyc-22.svg' },
    { name: 'Вощёная бумага', path: '/assets/icons/recyc-23.svg' },

    { name: 'Металлы', path: '' },
    { name: 'Сталь', path: '/assets/icons/recyc-40.svg' },
    { name: 'Алюминий', path: '/assets/icons/recyc-41.svg' },

    { name: 'Органические материалы природного происхождения', path: '' },
    { name: 'Древесина', path: '/assets/icons/recyc-50.svg' },
    { name: 'Пробка', path: '/assets/icons/recyc-51.svg' },
    { name: 'Хлопок', path: '/assets/icons/recyc-60.svg' },
    { name: 'Джутовое волокно', path: '/assets/icons/recyc-61.svg' },

    { name: 'Стекло', path: '' },
    { name: 'Бесцветное стекло', path: '/assets/icons/recyc-70.svg' },
    { name: 'Зелёное стекло', path: '/assets/icons/recyc-71.svg' },
    { name: 'Коричневое стекло', path: '/assets/icons/recyc-72.svg' },
    { name: 'Тёмно-коричневое стекло', path: '/assets/icons/recyc-73.svg' },
    { name: 'Светло-коричневое стекло', path: '/assets/icons/recyc-74.svg' },
    { name: 'Стекло с малым содержанием свинца', path: '/assets/icons/recyc-75.svg' },
    { name: 'Хрусталь', path: '/assets/icons/recyc-76.svg' },
    { name: 'Стекло, покрытое медью', path: '/assets/icons/recyc-77.svg' },
    { name: 'Стекло, покрытое серебром', path: '/assets/icons/recyc-78.svg' },
    { name: 'Позолоченное стекло', path: '/assets/icons/recyc-79.svg' },

    { name: 'Композиционные материалы', path: '' },
    { name: 'Бумага (картон) / различные материалы', path: '/assets/icons/recyc-80.svg' },
    { name: 'Бумага (картон) / пластик', path: '/assets/icons/recyc-81.svg' },
    { name: 'Бумага (картон) / алюминий', path: '/assets/icons/recyc-82.svg' },
    { name: 'Бумага (картон) / белая жесть', path: '/assets/icons/recyc-83.svg' },
    { name: 'Бумага (картон) / пластик / алюминий', path: '/assets/icons/recyc-84.svg' },
    { name: 'Бумага (картон) / пластик / алюминий / жесть', path: '/assets/icons/recyc-85.svg' },
    { name: 'Пластик / алюминий', path: '/assets/icons/recyc-90.svg' },
    { name: 'Пластик / белая жесть', path: '/assets/icons/recyc-91.svg' },
    { name: 'Пластик / различные металлы', path: '/assets/icons/recyc-92.svg' },
    { name: 'Стекло / пластик', path: '/assets/icons/recyc-95.svg' },
    { name: 'Стекло / алюминий', path: '/assets/icons/recyc-96.svg' },
    { name: 'Стекло / белая жесть', path: '/assets/icons/recyc-97.svg' },
    { name: 'Стекло / различные металлы', path: '/assets/icons/recyc-98.svg' },

    { name: 'Батареи и аккумуляторы', path: '' },
    { name: 'Литиевый элемент', path: '/assets/icons/recyc-b-liion.svg' },
    { name: 'Никель-кадмиевый аккумулятор', path: '/assets/icons/recyc-b-nicd.svg' },
    { name: 'Никель-металл-гидридный аккумулятор', path: '/assets/icons/recyc-b-nimh.svg' },
    { name: 'Свинцово-кислотный аккумулятор', path: '/assets/icons/recyc-b-pb.svg' },
];